kind: Deployment
apiVersion: apps/v1
metadata:
  name: gceme-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      env: staging
  template:
    metadata:
      name: backend
      labels:
        env: staging
    spec:
      containers:
      - name: backend
        env:
        - name: VERSION
          value: staging
