apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
    name: kustomize-build
spec:
  inputs:
    resources:
    - name: kustomize-source
      type: git
    params:
    - name: pathToKustomization
      type: string
      description: The path to the kustomization to build
      default: /workspace/kustomize-source/
  outputs:
      resources:
      - name: kustomizeYaml
        type: storage
  steps:
  - name: build-and-store
    image: viglesiasce/kustomize-gsutil
    command:
    - sh
    args:
    - -c
    - |
      mkdir -p /workspace/output/kustomizeYaml
      kustomize build ${inputs.params.pathToKustomization} \
                -o /workspace/output/kustomizeYaml/kustomize.yaml
