apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/vic-cd-demo/sample-app-backend-dev
    context: cmd/backend
  - image: gcr.io/vic-cd-demo/sample-app-frontend-dev
    context: cmd/frontend
  tagPolicy:
    sha256: {}
deploy:
  kustomize: {}
