steps:
- name: gcr.io/kaniko-project/executor:latest
  id: build
  waitFor: ['-']
  args:
  - "--context=dir:///workspace/cmd/frontend"
  - "--destination=gcr.io/$PROJECT_ID/sample-app-frontend:$COMMIT_SHA"
  - "--cache"
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'test'
  waitFor: ['-']
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
     GOPATH=/root/go
     mkdir -p /root/go/src
     ln -s /workspace/cmd/frontend /root/go/src/frontend
     cd /root/go/src/frontend
     go test
options:
 machineType: 'N1_HIGHCPU_8'