steps:
- name: gcr.io/kaniko-project/executor:latest
  id: build
  waitFor: ['-']
  args:
  - "--context=dir:///workspace/cmd/backend"
  - "--destination=gcr.io/$PROJECT_ID/sample-app-backend:$COMMIT_SHA"
  - "--cache"
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'test'
  waitFor: ['-']
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
     GOPATH=/root/go
     mkdir -p /root/go/src
     ln -s /workspace/cmd/backend /root/go/src/backend
     cd /root/go/src/backend
     go test
- name: 'gcr.io/$PROJECT_ID/kustomize'
  id: 'create-yaml'
  waitFor: ['-']
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
     mkdir -p /workspace/yaml
     /kustomize build cmd/backend/k8s/production > /workspace/yaml/backend-production.yaml
     /kustomize build cmd/backend/k8s/staging > /workspace/yaml/backend-staging.yaml
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'upload-yaml'
  waitFor: ['create-yaml']
  args:
  - cp /workspace/yaml/* gs://vic-cd-demo-k8s-yaml/
options:
 machineType: 'N1_HIGHCPU_32'